//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("StoreModel", "Dapartment_Manager", "Employees", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Checkout.Model.Employee), "Departments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Checkout.Model.Department), true)]
[assembly: EdmRelationshipAttribute("StoreModel", "Department_Product", "Departments", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Checkout.Model.Department), "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Checkout.Model.Product), true)]
[assembly: EdmRelationshipAttribute("StoreModel", "Distributor_Product", "Distributors", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Checkout.Model.Distributor), "Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Checkout.Model.Product), true)]
[assembly: EdmRelationshipAttribute("StoreModel", "Contact_Distributor", "DistributorContact", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Checkout.Model.DistributorContact), "Distributor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Checkout.Model.Distributor), true)]

#endregion

namespace Checkout.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StoreEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StoreEntities object using the connection string found in the 'StoreEntities' section of the application configuration file.
        /// </summary>
        public StoreEntities() : base("name=StoreEntities", "StoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StoreEntities object.
        /// </summary>
        public StoreEntities(string connectionString) : base(connectionString, "StoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StoreEntities object.
        /// </summary>
        public StoreEntities(EntityConnection connection) : base(connection, "StoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Department> Departments
        {
            get
            {
                if ((_Departments == null))
                {
                    _Departments = base.CreateObjectSet<Department>("Departments");
                }
                return _Departments;
            }
        }
        private ObjectSet<Department> _Departments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DistributorContact> DistributorContacts
        {
            get
            {
                if ((_DistributorContacts == null))
                {
                    _DistributorContacts = base.CreateObjectSet<DistributorContact>("DistributorContacts");
                }
                return _DistributorContacts;
            }
        }
        private ObjectSet<DistributorContact> _DistributorContacts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Distributor> Distributors
        {
            get
            {
                if ((_Distributors == null))
                {
                    _Distributors = base.CreateObjectSet<Distributor>("Distributors");
                }
                return _Distributors;
            }
        }
        private ObjectSet<Distributor> _Distributors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Departments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDepartments(Department department)
        {
            base.AddObject("Departments", department);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DistributorContacts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDistributorContacts(DistributorContact distributorContact)
        {
            base.AddObject("DistributorContacts", distributorContact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Distributors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDistributors(Distributor distributor)
        {
            base.AddObject("Distributors", distributor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoreModel", Name="Department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Department : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Department object.
        /// </summary>
        /// <param name="department_ID">Initial value of the Department_ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Department CreateDepartment(global::System.Int32 department_ID, global::System.String name)
        {
            Department department = new Department();
            department.Department_ID = department_ID;
            department.Name = name;
            return department;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Department_ID
        {
            get
            {
                return _Department_ID;
            }
            set
            {
                if (_Department_ID != value)
                {
                    OnDepartment_IDChanging(value);
                    ReportPropertyChanging("Department_ID");
                    _Department_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Department_ID");
                    OnDepartment_IDChanged();
                }
            }
        }
        private global::System.Int32 _Department_ID;
        partial void OnDepartment_IDChanging(global::System.Int32 value);
        partial void OnDepartment_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Manager_ID
        {
            get
            {
                return _Manager_ID;
            }
            set
            {
                OnManager_IDChanging(value);
                ReportPropertyChanging("Manager_ID");
                _Manager_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Manager_ID");
                OnManager_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Manager_ID;
        partial void OnManager_IDChanging(Nullable<global::System.Int32> value);
        partial void OnManager_IDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreModel", "Dapartment_Manager", "Employees")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("StoreModel.Dapartment_Manager", "Employees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("StoreModel.Dapartment_Manager", "Employees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("StoreModel.Dapartment_Manager", "Employees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("StoreModel.Dapartment_Manager", "Employees", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreModel", "Department_Product", "Products")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("StoreModel.Department_Product", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("StoreModel.Department_Product", "Products", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoreModel", Name="Distributor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Distributor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Distributor object.
        /// </summary>
        /// <param name="distributor_ID">Initial value of the Distributor_ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Distributor CreateDistributor(global::System.Int32 distributor_ID, global::System.String name)
        {
            Distributor distributor = new Distributor();
            distributor.Distributor_ID = distributor_ID;
            distributor.Name = name;
            return distributor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Distributor_ID
        {
            get
            {
                return _Distributor_ID;
            }
            set
            {
                if (_Distributor_ID != value)
                {
                    OnDistributor_IDChanging(value);
                    ReportPropertyChanging("Distributor_ID");
                    _Distributor_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Distributor_ID");
                    OnDistributor_IDChanged();
                }
            }
        }
        private global::System.Int32 _Distributor_ID;
        partial void OnDistributor_IDChanging(global::System.Int32 value);
        partial void OnDistributor_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Contact_ID
        {
            get
            {
                return _Contact_ID;
            }
            set
            {
                OnContact_IDChanging(value);
                ReportPropertyChanging("Contact_ID");
                _Contact_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Contact_ID");
                OnContact_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Contact_ID;
        partial void OnContact_IDChanging(Nullable<global::System.Int32> value);
        partial void OnContact_IDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreModel", "Distributor_Product", "Products")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("StoreModel.Distributor_Product", "Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("StoreModel.Distributor_Product", "Products", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreModel", "Contact_Distributor", "DistributorContact")]
        public DistributorContact DistributorContact
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DistributorContact>("StoreModel.Contact_Distributor", "DistributorContact").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DistributorContact>("StoreModel.Contact_Distributor", "DistributorContact").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DistributorContact> DistributorContactReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DistributorContact>("StoreModel.Contact_Distributor", "DistributorContact");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DistributorContact>("StoreModel.Contact_Distributor", "DistributorContact", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoreModel", Name="DistributorContact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DistributorContact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DistributorContact object.
        /// </summary>
        /// <param name="contact_ID">Initial value of the Contact_ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static DistributorContact CreateDistributorContact(global::System.Int32 contact_ID, global::System.String name)
        {
            DistributorContact distributorContact = new DistributorContact();
            distributorContact.Contact_ID = contact_ID;
            distributorContact.Name = name;
            return distributorContact;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Contact_ID
        {
            get
            {
                return _Contact_ID;
            }
            set
            {
                if (_Contact_ID != value)
                {
                    OnContact_IDChanging(value);
                    ReportPropertyChanging("Contact_ID");
                    _Contact_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Contact_ID");
                    OnContact_IDChanged();
                }
            }
        }
        private global::System.Int32 _Contact_ID;
        partial void OnContact_IDChanging(global::System.Int32 value);
        partial void OnContact_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private Nullable<global::System.Int32> _Phone;
        partial void OnPhoneChanging(Nullable<global::System.Int32> value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private Nullable<global::System.Int32> _Fax;
        partial void OnFaxChanging(Nullable<global::System.Int32> value);
        partial void OnFaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Website
        {
            get
            {
                return _Website;
            }
            set
            {
                OnWebsiteChanging(value);
                ReportPropertyChanging("Website");
                _Website = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Website");
                OnWebsiteChanged();
            }
        }
        private global::System.String _Website;
        partial void OnWebsiteChanging(global::System.String value);
        partial void OnWebsiteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreModel", "Contact_Distributor", "Distributor")]
        public EntityCollection<Distributor> Distributors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Distributor>("StoreModel.Contact_Distributor", "Distributor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Distributor>("StoreModel.Contact_Distributor", "Distributor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoreModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="employee_ID">Initial value of the Employee_ID property.</param>
        /// <param name="first_Name">Initial value of the First_Name property.</param>
        /// <param name="last_Name">Initial value of the Last_Name property.</param>
        /// <param name="position">Initial value of the Position property.</param>
        public static Employee CreateEmployee(global::System.Int32 employee_ID, global::System.String first_Name, global::System.String last_Name, global::System.String position)
        {
            Employee employee = new Employee();
            employee.Employee_ID = employee_ID;
            employee.First_Name = first_Name;
            employee.Last_Name = last_Name;
            employee.Position = position;
            return employee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Employee_ID
        {
            get
            {
                return _Employee_ID;
            }
            set
            {
                if (_Employee_ID != value)
                {
                    OnEmployee_IDChanging(value);
                    ReportPropertyChanging("Employee_ID");
                    _Employee_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Employee_ID");
                    OnEmployee_IDChanged();
                }
            }
        }
        private global::System.Int32 _Employee_ID;
        partial void OnEmployee_IDChanging(global::System.Int32 value);
        partial void OnEmployee_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String First_Name
        {
            get
            {
                return _First_Name;
            }
            set
            {
                OnFirst_NameChanging(value);
                ReportPropertyChanging("First_Name");
                _First_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("First_Name");
                OnFirst_NameChanged();
            }
        }
        private global::System.String _First_Name;
        partial void OnFirst_NameChanging(global::System.String value);
        partial void OnFirst_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Last_Name
        {
            get
            {
                return _Last_Name;
            }
            set
            {
                OnLast_NameChanging(value);
                ReportPropertyChanging("Last_Name");
                _Last_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Last_Name");
                OnLast_NameChanged();
            }
        }
        private global::System.String _Last_Name;
        partial void OnLast_NameChanging(global::System.String value);
        partial void OnLast_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private global::System.String _Position;
        partial void OnPositionChanging(global::System.String value);
        partial void OnPositionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreModel", "Dapartment_Manager", "Departments")]
        public EntityCollection<Department> Departments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Department>("StoreModel.Dapartment_Manager", "Departments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Department>("StoreModel.Dapartment_Manager", "Departments", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoreModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="product_ID">Initial value of the Product_ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="brand">Initial value of the Brand property.</param>
        /// <param name="barcode">Initial value of the Barcode property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="aisle">Initial value of the Aisle property.</param>
        /// <param name="date_Added">Initial value of the Date_Added property.</param>
        public static Product CreateProduct(global::System.Int32 product_ID, global::System.String name, global::System.String brand, global::System.Int64 barcode, global::System.Decimal price, global::System.Int32 aisle, global::System.DateTime date_Added)
        {
            Product product = new Product();
            product.Product_ID = product_ID;
            product.Name = name;
            product.Brand = brand;
            product.Barcode = barcode;
            product.Price = price;
            product.Aisle = aisle;
            product.Date_Added = date_Added;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Product_ID
        {
            get
            {
                return _Product_ID;
            }
            set
            {
                if (_Product_ID != value)
                {
                    OnProduct_IDChanging(value);
                    ReportPropertyChanging("Product_ID");
                    _Product_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Product_ID");
                    OnProduct_IDChanged();
                }
            }
        }
        private global::System.Int32 _Product_ID;
        partial void OnProduct_IDChanging(global::System.Int32 value);
        partial void OnProduct_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Display_Name
        {
            get
            {
                return _Display_Name;
            }
            set
            {
                OnDisplay_NameChanging(value);
                ReportPropertyChanging("Display_Name");
                _Display_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Display_Name");
                OnDisplay_NameChanged();
            }
        }
        private global::System.String _Display_Name;
        partial void OnDisplay_NameChanging(global::System.String value);
        partial void OnDisplay_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Brand
        {
            get
            {
                return _Brand;
            }
            set
            {
                OnBrandChanging(value);
                ReportPropertyChanging("Brand");
                _Brand = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Brand");
                OnBrandChanged();
            }
        }
        private global::System.String _Brand;
        partial void OnBrandChanging(global::System.String value);
        partial void OnBrandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Barcode
        {
            get
            {
                return _Barcode;
            }
            set
            {
                if (_Barcode != value)
                {
                    OnBarcodeChanging(value);
                    ReportPropertyChanging("Barcode");
                    _Barcode = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Barcode");
                    OnBarcodeChanged();
                }
            }
        }
        private global::System.Int64 _Barcode;
        partial void OnBarcodeChanging(global::System.Int64 value);
        partial void OnBarcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Distributor_ID
        {
            get
            {
                return _Distributor_ID;
            }
            set
            {
                OnDistributor_IDChanging(value);
                ReportPropertyChanging("Distributor_ID");
                _Distributor_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Distributor_ID");
                OnDistributor_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Distributor_ID;
        partial void OnDistributor_IDChanging(Nullable<global::System.Int32> value);
        partial void OnDistributor_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Department_ID
        {
            get
            {
                return _Department_ID;
            }
            set
            {
                OnDepartment_IDChanging(value);
                ReportPropertyChanging("Department_ID");
                _Department_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Department_ID");
                OnDepartment_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _Department_ID;
        partial void OnDepartment_IDChanging(Nullable<global::System.Int32> value);
        partial void OnDepartment_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Aisle
        {
            get
            {
                return _Aisle;
            }
            set
            {
                OnAisleChanging(value);
                ReportPropertyChanging("Aisle");
                _Aisle = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Aisle");
                OnAisleChanged();
            }
        }
        private global::System.Int32 _Aisle;
        partial void OnAisleChanging(global::System.Int32 value);
        partial void OnAisleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date_Added
        {
            get
            {
                return _Date_Added;
            }
            set
            {
                OnDate_AddedChanging(value);
                ReportPropertyChanging("Date_Added");
                _Date_Added = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date_Added");
                OnDate_AddedChanged();
            }
        }
        private global::System.DateTime _Date_Added;
        partial void OnDate_AddedChanging(global::System.DateTime value);
        partial void OnDate_AddedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreModel", "Department_Product", "Departments")]
        public Department Department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("StoreModel.Department_Product", "Departments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("StoreModel.Department_Product", "Departments").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Department> DepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("StoreModel.Department_Product", "Departments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Department>("StoreModel.Department_Product", "Departments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreModel", "Distributor_Product", "Distributors")]
        public Distributor Distributor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Distributor>("StoreModel.Distributor_Product", "Distributors").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Distributor>("StoreModel.Distributor_Product", "Distributors").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Distributor> DistributorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Distributor>("StoreModel.Distributor_Product", "Distributors");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Distributor>("StoreModel.Distributor_Product", "Distributors", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
